Completed Exercise 6
mlhaus/KCC-Intro-Tue-Thr pull request #27
Opened 2020-10-27 06:48 UTC by TreshaSar

2020-10-28 15:26 UTC, mlhaus commented on sarabia-exercise6.py
> +    print("Numbers that are greater than " + str(n))
If n is 60, your code will print `Numbers that are greater than 60`. You also need to print the result array list.

2020-10-28 15:28 UTC, mlhaus commented on sarabia-exercise6.py
> +  howMany = getNum("Please enter a number between 10 and 20.", 10.0, 20.0)
Decimals are not necessary here. This number will be used to determine how many random numbers to generate. For example, you can't generate 15.5 numbers.

2020-10-28 15:28 UTC, mlhaus requested changes
Looks good. Make these two corrections to get full credit.

2020-10-29 21:46 UTC, TreshaSar commented
**I fixed the 2 areas and removed the decimals to get full credit for this assignment. Thank you for the feedback!**  👍

2020-10-31 01:23 UTC, merged